In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv('../Data/data_transformacion_limpieza_customer.csv')

In [3]:
import sys
sys.path.append("../SRC")

import sp_limpieza_customer as sp

In [4]:
sp.eda_preliminar(df)

,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID,Join_Year
10800,8521,1,2,2012-12-07,27,4e2da5aa-2528-45aa-b8fc-085cbe875595,2012
4520,48379,1,1,2012-10-12,22,52fb829c-4c82-4c46-8286-5e268f169eb1,2012
25469,59164,1,2,2013-05-05,22,00665d1e-171b-44b0-b0de-47493a4aa0b4,2013
6343,89841,2,0,2012-10-15,8,8ccf0b0f-1fae-4ba6-bb51-c8633295b1f7,2012
20137,35680,0,1,2013-04-28,19,b2538d03-ef7d-44a3-bd48-95b24a704f7c,2013

----------------
INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43170 entries, 0 to 43169
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Income             43170 non-null  int64
 1   Kidhome            43170 non-null  int64
 2   Teenhome           43170 non-null  int64
 3   Dt_Customer        43170 non-null  object
 4   NumWebVisitsMonth  43170 non-null  int64
 5   ID                 43170 non-null  object
 6   Join_Year          43170 non-null  int64
dtypes: int64(5), object(2)
memory usage: 2.3+ MB

None

----------------
NULOS

Income               0.0
Kidhome              0.0
Teenhome             0.0
Dt_Customer          0.0
NumWebVisitsMonth    0.0
ID                   0.0
Join_Year            0.0
dtype: float64

----------------
DUPLICADOS
0
----------------
VALUE COUNTS
Dt_Customer
2012-08-10    79
2012-01-11    79
2012-12-28    75
2012-12-21    72
2012-11-25    72
              ..
2013-06-05    15
2013-02-12    15
2013-09-03    15
2013-10-18    13
2013-10-24    12
Name: count, Length: 1096, dtype: int64
---------------------------
ID
089b39d8-e4d0-461b-87d4-814d71e0e079    1
38708e69-8996-4d51-956a-d422fd78872d    1
7218c062-4571-4fd9-8bad-c6a09ad1eb5d    1
853e4074-829e-47e4-9287-06b4cb0f814f    1
a185385b-b614-423b-9932-a132ed02eed1    1
                                       ..
8e1e500d-de2a-4e14-b027-20983ebaeeb9    1
bdee816d-7f9d-442a-99e1-cf259021f8f5    1
8d3ae2ee-5363-4508-ac65-cbecc78a08bb    1
4601e86a-18c4-473c-8467-fb16e838be7d    1
9727bc06-c11a-461a-a5bb-3d210467cc2a    1
Name: count, Length: 43170, dtype: int64
---------------------------

In [5]:
df.rename(columns={
    'Kidhome': 'Kid_Home',
    'Teenhome': 'Teen_Home',
    'NumWebVisitsMonth': 'Num_Web_Visits_Month'
}, inplace=True)

In [7]:
df['Dt_Customer'] = pd.to_datetime(df['Dt_Customer'])

In [8]:
df.sample(5)

,Income,Kid_Home,Teen_Home,Dt_Customer,Num_Web_Visits_Month,ID,Join_Year
12153,42711,0,2,2012-02-27,11,8eb63930-6e51-45a4-95f4-72bdbd5ae44f,2012
12172,27611,2,0,2012-09-16,23,1ff36b7d-e141-4723-8774-7598cedad5b1,2012
8997,53182,1,2,2012-06-09,19,3aa845c7-8f1e-4edd-be02-86700b757120,2012
37930,152744,1,0,2014-02-09,25,38f2c326-0445-490e-8042-f1d2a0780a52,2014
11285,148013,1,1,2012-09-04,32,4ee7cec5-a50e-491b-ab49-a94620beb900,2012